### ISSUE TITLE
Invalid magic of KFC_DIR file

### ISSUE THREAD

**Issue by secure-77** [Ekey/KG.Data.Tool#2]
Hey,

I wasn't able to run it on enshrouded build 491573, always gives me `Invalid magic of KFC_DIR file!`

```bash
KG.Unpacker.exe "D:\SteamLibrary\steamapps\common\Enshrouded\enshrouded.kfc_data" "D:\SteamLibrary\steamapps\common\Enshrouded\unpacked"
````

![image](https://github.com/Ekey/KG.Data.Tool/assets/31564517/c1e606e4-b2aa-4fee-b897-8c34fc5588fb)

**Comment by Ekey** [comment]
You need to specify the **enshrouded.kfc_dir** file instead of **enshrouded.kfc_data**.

**Comment by secure-77** [comment]
Thanks, this is working 👍 
Any tip how to open / edit these files (besides a Hex Editor)? I saw some files starting with the magic bytes "CRPF"

**Comment by Ekey** [comment]
> Any tip how to open / edit these files (besides a Hex Editor)?

Currently no

> I saw some files starting with the magic bytes "CRPF"

I already answered about CRPF [here](https://github.com/Ekey/KG.Data.Tool/issues/1#issuecomment-1926103868)

**Comment by secure-77** [comment]
JFYI: There is some other tool, they have also discord where you can discuss about modding: https://github.com/ndoa/kfc-tools
